# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
permalink: /post/:title
title: the code reporter
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Apprenticeship journal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pwdd.github.io" # the base hostname & protocol for your site
twitter_username: _pwdd
github_username:  pwdd

# Build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets
  style: compressed
gems:
 - jekyll-coffeescript
excerpt_separator: <!--more-->

